services:
  postgres:
    image: 'postgres:18.0'
    container_name: desafio-tecnico
    environment:
      - 'POSTGRES_DB=db_deliver_it'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
