services:
  postgres:
    image: 'postgres:18.0'
    container_name: desafio-tecnico
    environment:
      - 'POSTGRES_DB=db_deliver_it'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
    container_name: desafio-tecnico
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/db_deliver_it
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - desafio-network

volumes:
  postgres-data:

networks:
  desafio-network:
    driver: bridge