CREATE TABLE contas_pg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    valor_original NUMERIC(19, 2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE NOT NULL,
    dias_atraso INTEGER NOT NULL DEFAULT 0,
    valor_corrigido NUMERIC(19, 2),
    regra_aplicada VARCHAR(25),
    descricao_regra VARCHAR(110),

    CONSTRAINT chk_vl_original_positivo CHECK (valor_original > 0),
    CONSTRAINT chk_dias_atraso_positivo CHECK (dias_atraso >= 0)
);